export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const LOAD_CITIES_SUCCESS = 'LOAD_CITIES_SUCCESS';
export const LOAD_CITY_SUCCESS = 'LOAD_CITY_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_CITY_SUCCESS = 'CREATE_CITY_SUCCESS';
export const UPDATE_CITY_SUCCESS = 'UPDATE_CITY_SUCCESS';
export const DELETE_CITY_SUCCESS = 'DELETE_CITY_SUCCESS';